<a href="https://colab.research.google.com/github/Impossiblepretext/Experiment_No.12/blob/main/Experiment_No_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 Experiment 12: To perform processing on the data and deal with missing values

 Name: Ansh Srivastava

 PRN:25070123015

 Branch:F.Y Btech(Entc)

 Batch: A1

In [ ]:
import pandas as pd
import numpy as np
df1=pd.DataFrame({'C1':[11,21,np.nan],'C2':[15,np.nan,np.nan],'C3':[10,20,30]})
df1

     C1    C2  C3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [ ]:
df1.isna()

      C1     C2     C3
0  False  False  False
1  False   True  False
2   True   True  False

In [ ]:
df1.isna().sum()

C1    1
C2    2
C3    0
dtype: int64

In [ ]:
df1.dropna()

     C1    C2  C3
0  11.0  15.0  10

In [ ]:
df1.fillna(value="DEFAULT")

        C1       C2  C3
0     11.0     15.0  10
1     21.0  DEFAULT  20
2  DEFAULT  DEFAULT  30

In [ ]:
df1.fillna(df1.mean())#mean values of columns are calculated

     C1    C2  C3
0  11.0  15.0  10
1  21.0  15.0  20
2  16.0  15.0  30

In [ ]:
import pandas as pd
data={
    "Roll No":[1,2,3,4,5],
    "Name":["A","B","C","D","E"],
    "Age":[20,"-",22,23,"24"],
    "Marks":[90,91,92,93,94],
    "Department":["CSE","IT","CSE","CSE","ETC"],
    "Admission_Date":["01-06-2023","03-06-2023","05-06-2023","07-06-2023","16-06-2023"]
}
df=pd.DataFrame(data)
df.to_csv("data.csv",index=False)
df=pd.read_csv("data.csv")
print(df)

   Roll No Name Age  Marks Department Admission_Date
0        1    A  20     90        CSE     01-06-2023
1        2    B   -     91         IT     03-06-2023
2        3    C  22     92        CSE     05-06-2023
3        4    D  23     93        CSE     07-06-2023
4        5    E  24     94        ETC     16-06-2023

In [ ]:
df.replace("-",np.nan,inplace=True)
#convert colums to numeric where needed
df["Age"]=pd.to_numeric(df["Age"],errors="coerce")
df["Marks"]=pd.to_numeric(df["Marks"],errors="coerce")
df

   Roll No Name   Age  Marks Department Admission_Date
0        1    A  20.0     90        CSE     01-06-2023
1        2    B   NaN     91         IT     03-06-2023
2        3    C  22.0     92        CSE     05-06-2023
3        4    D  23.0     93        CSE     07-06-2023
4        5    E  24.0     94        ETC     16-06-2023

In [ ]:
#step 3 CHeck missing values
print("\nMissing Values:")
print(df.isnull().sum())

Missing Values:
Roll No           0
Name              0
Age               1
Marks             0
Department        0
Admission_Date    0
dtype: int64

In [ ]:
#fill missing range  with mean
df["Age"].fillna(df["Age"].mean(),inplace=True)
df

/tmp/ipykernel_522/625579121.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(),inplace=True)

   Roll No Name    Age  Marks Department Admission_Date
0        1    A  20.00     90        CSE     01-06-2023
1        2    B  22.25     91         IT     03-06-2023
2        3    C  22.00     92        CSE     05-06-2023
3        4    D  23.00     93        CSE     07-06-2023
4        5    E  24.00     94        ETC     16-06-2023

In [ ]:
#step 5: Fix inconsistent text formatting
df["Department"]=df["Department"].str.upper()
df

   Roll No Name    Age  Marks Department Admission_Date
0        1    A  20.00     90        CSE     01-06-2023
1        2    B  22.25     91         IT     03-06-2023
2        3    C  22.00     92        CSE     05-06-2023
3        4    D  23.00     93        CSE     07-06-2023
4        5    E  24.00     94        ETC     16-06-2023

In [ ]:
#step 6: Convert Admission_Date to standard date time
df["Admission_Date"]=pd.to_datetime(df["Admission_Date"],errors="coerce")
df

   Roll No Name    Age  Marks Department Admission_Date
0        1    A  20.00     90        CSE     2023-01-06
1        2    B  22.25     91         IT     2023-03-06
2        3    C  22.00     92        CSE     2023-05-06
3        4    D  23.00     93        CSE     2023-07-06
4        5    E  24.00     94        ETC            NaT

In [ ]:
# step 7: cleanded dataset
df.to_csv("cleaned_data.csv",index=False)
df

   Roll No Name    Age  Marks Department Admission_Date
0        1    A  20.00     90        CSE     2023-01-06
1        2    B  22.25     91         IT     2023-03-06
2        3    C  22.00     92        CSE     2023-05-06
3        4    D  23.00     93        CSE     2023-07-06
4        5    E  24.00     94        ETC            NaT

In [ ]:
# step 8: save cleaned dataset
df.to_csv("cleaned_student_data.csv",index=False)
print("\nCleaned CSV file saved as cleaned_student_data.csv ")

Cleaned CSV file saved as cleaned_student_data.csv

In [ ]:
#  upload the data  sent
import pandas as pd
import numpy  as np
df=pd.read_csv("/content/Cars93.csv")
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [ ]:
# check missing value
df.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

In [ ]:
# IMputing the  missing value
df['Luggage.room']=df['Luggage.room'].fillna(value=df['Luggage.room'].mean())
df.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room       0
dtype: int64

In [ ]:
df["AirBags"]=df['AirBags'].fillna(value=df['AirBags'].mode().values[0])
df.isna().sum()

Manufacturer      0
Model             0
Type              0
Price             0
MPG.city          0
AirBags           0
Horsepower        0
Passengers        0
Rear.seat.room    2
Luggage.room      0
dtype: int64